### ISSUE TITLE
Airport Proximity (unknown sensor) always has temperature of 129°C; Switchable graphics gives incorrect temperature measurement

### ISSUE THREAD

**Issue by jintakhan** [kozlek/HWSensors#188]
This is at an idle state. Notice how the GPU die sensor shows 128°C, and occasionally shows accurate temperature. The measurement is always correct when the GPU is in use; it is often like this when the IGP is in use.
The "Airport Proximity" sensor is always at 129°C and generates a ton of Growl notifications.
![screen shot 2014-02-12 at 10 55 17 pm](https://f.cloud.github.com/assets/6274214/2156653/cf3eae3a-9462-11e3-862a-fbcadc66c5ca.png)

**Comment by davipt** [comment]
From this thread I can't understand if those AirPort Proximity at 129ºC and the 3 GPU values consuming 64 and 32 Amperes are values to be ignored (hence why not ignored directly by the app) of if there is anything we can help to improve them? I don't want to open a new bug if they are to be ignored (just say "ignore them"), but can open a new bug and present my laptop's data if it helps.
