### ISSUE TITLE
PWM Fan Control Broken — EVGA Stinger Z87

### ISSUE THREAD

**Issue by hallee** [kozlek/HWSensors#239]
My motherboard seems to be unsupported by HWSensors; I can't find the 'product_name' anywhere in the LPCSensors.kext plist. The product name is: 111-HW-E872
![screen shot 2014-08-13 at 12 11 33 pm](https://cloud.githubusercontent.com/assets/784999/3909380/f35dffa8-230c-11e4-9696-7844c9b3a44b.png)

Everything seems to be working, including _reporting_ of fan speeds, except for setting fan speeds. I can't change the speeds at all, as it seems the minimum and maximum speed are both set to 0 RPM. (Below, you'll see two of the PWM headers aren't reporting a speed; this is because my fans are stopped. The one reporting PWM header is my water pump, but I can't change speeds on that either.)

No controls appear on hover, and other fan speed utilities are unable to change speeds (stuck at 0 RPM).

![screen shot 2014-08-13 at 12 11 52 pm](https://cloud.githubusercontent.com/assets/784999/3909400/3361fda2-230d-11e4-83b0-b961872341d0.png)

**Is there any chance you could add this motherboard?** Or is there any way I could add it myself, and/or change the range of possible values for my fans?

**Comment by Lord-Kamina** [comment]
Hello, I was just wondering whether there's been any change/progress re: Fintek chips?
Using an MSI P67A-GD55 (B3), i.e. F71899AD; previously no fan control pop-up or anything. I manually added the FxMn, FxMx and FxTg keys to FakeSMC's info.plist and now I do get the option to turn fan control on but it obviously does not work.
