### ISSUE TITLE
Asus p5w dh deluxe fans stop when fakesmc with LPCSensors.kext is loaded

### ISSUE THREAD

**Issue by piromanneo** [kozlek/HWSensors#257]
Hi !

I would like to report this strange bug in your LPCSensors.kext that stops my fans during boot of OS X 10.10. It looks like something in kext lows their voltage (as seen by fan led) every second until their voltage is too low to spin the fans. Fan leds blink every second as they try to start.

Problem is that temperatures rise very high under load and cause system instability.

Now i removed LPCSENSORS.kext from FakeSmc and fans spin, but as expected they are not detected nor voltages and other MB temperatures.  

 I am using the last build 6.11.1328

Board is Asus p5w dh deluxe ver 1.03g bios 3002 I/O chip is Winbond W83627EHF. (tried all fan ports, all bios settings (Asus quiet AI off/on, manual profiles (quiet, optimal, performance) all settings did not change everything.

Btw for future releases I would love to see that I can set my own temperature level alarm eg. cpu alarm at 60c

**Comment by mattgit** [comment]
same on asus p5q.
hwmonitor is awesome, but this is a terrible bug and can cause some hardware damage, please fix it...

thank for your great work

**Comment by CristianDeluxe** [comment]
Same with SABERTOOTH X58 motherboard :(

**Comment by axmanA** [comment]
Hi there,
had exactly the same problem and some little tweaking got me success. If somebody wants to try out go to:
https://github.com/axmanA/HWSensors/releases/tag/6.14_W836xx
Please comment back.

regards

**Comment by barnumfr** [comment]
hi axmanA,

your new version solve the PB on my motherboard (P6T WS pro)

Thanks,
Barnumfr

**Comment by axmanA** [comment]
Hi Barnumfr,

thats cool ...

**Comment by guiorlle** [comment]
Hi axmanA,

For me too :):):):)

Your new version solve the PB on my motherboard (P5Q Pro Turbo)

Thanks,
Guiorlle

**Comment by robross0606** [comment]
Could anyone post a compiled version of this?

**Comment by axmanA** [comment]
Go to the link above and there you find the link to the compiled version. Kozlek have merged the changes.

**Comment by robross0606** [comment]
Thanks.  Do you know what version should have the changes merged upstream?  I'm still having this issue with the latest update from Koslek.

**Comment by axmanA** [comment]
merged here 
https://github.com/kozlek/HWSensors/commit/8b41b6f8426d4bf4929ce03d750ea32f7536579c
2 month ago (22nd of March)
Any newer release should include the fix.
