### ISSUE TITLE
Dark Mode icons

### ISSUE THREAD

**Issue by benwa** [kozlek/HWSensors#258]
With 10.10's new Dark Mode, the icons for HWMonitor is invisible.  This can be fixed relatively simple by switching the logic into a template.  A quick example can be found [here](http://www.leebrimelow.com/prepping-icons-for-yosemite-dark-mode).

**Comment by perfaram** [comment]
Close ?

**Comment by tluck** [comment]
use 1364 - icons works for dark menu mode. just don't use the green or red icon.

**Comment by perfaram** [comment]
So this issue can be closed ?

**Comment by TuncTaylan** [comment]
The red and the green icons still won't show up in dark mode...

**Comment by kozlek** [comment]
TuncTaylan, thanks for pointed at. Fixed and committed.
