### ISSUE TITLE
Not battery data on new Magic Mouse 2 and new Magic keyboard

### ISSUE THREAD

**Issue by nohnaimer** [kozlek/HWSensors#323]
Hello,
Please help me.
I buy new Apple magic keyboard MLA22RU and apple Magic Mouse 2 MLA02Z
After connected, the HWsensors missing data on the state of the battery, how to fix it?
Original issue here: https://applelife.ru/threads/hwsensors.35928/page-29#post-584115
Thank you and sorry for my bad English.

**Comment by kozlek** [comment]
Sorry for late reply. Could you provide dump from IORegistryExporer?

**Comment by nohnaimer** [comment]
No problem https://cloud.mail.ru/public/1bdf/8HfNFGCAA

**Comment by kozlek** [comment]
Thanks! 

Try this version: http://hwsensors.com/public/HWMonitor.app.zip

**Comment by nohnaimer** [comment]
Thanks! Everything works fine!
![2016-07-12 8 22 47](https://cloud.githubusercontent.com/assets/8865830/16755918/e2d49b46-4809-11e6-87d9-9f0ed9e8471c.png)
