### ISSUE TITLE
updates on CPUID for SkyLake

### ISSUE THREAD

**Issue by tluck** [kozlek/HWSensors#340]
Please update cpuid.h with these cpu definitions for skylake. I found these in an apple open source file and use them to compile locally  - my cpuid is 0x4E for a laptop.

```
original:
#define CPUID_MODEL_SKYLAKE         0x5E
new:
#define CPUID_MODEL_SKYLAKE		0x4E
#define CPUID_MODEL_SKYLAKE_ULT		0x4E
#define CPUID_MODEL_SKYLAKE_ULX		0x4E
#define CPUID_MODEL_SKYLAKE_DT		0x5E
```

**Comment by kozlek** [comment]
Thanks! Added to the project: a242a8f514d73460bbda62aa0ff196fe17f730f3
