### ISSUE TITLE
Cosmetic suggestion: Use monospaced-digit font for menu bar item on 10.11 and newer

### ISSUE THREAD

**Issue by MrMage** [kozlek/HWSensors#345]
Hi,

First of all, thank you for the great work with HWSensors! The app is really helpful.

Currently, the menu bar item use a normal font for displaying temperatures. This doesn't look nice when there is e.g. one temperature with 11° and one with 44°, as the two will then have very different widths (which looks asymmetrical). Plus, all menu bar items to the left of HWSensors constantly move left and right because the HWSensors item's width changes whenever my temperatures change.

To improve this, would it be possible to use a monospaced-digit font for the menu bar item when available? On OS X 10.11 and newer, there is an API for that: https://developer.apple.com/reference/appkit/nsfont/1528205-monospaceddigitsystemfont

Thanks,
Daniel

**Comment by kozlek** [comment]
Thank you for suggestion. Added in 07ae765595d1c653ebf01cb9f26e4520e00fee21
