### ISSUE TITLE
Feature request: S.M.A.R.T. Error rate calculator for Seagate drives

### ISSUE THREAD

**Issue by jammi** [kozlek/HWSensors#357]
Since Seagate (ST-somethings) report the total amount of reads and seeks in a format that includes the total amount and errors in one, they always have insanely high raw numbers. To make sense of them, it's required to parse the binary value of the 48-bit number and split the first 16 bits as errors and last 32 bits as total. So what I suggest is displaying something like **(errors: \[number], total: \[number])** rather than, or in addition to the raw value.

Here's an article about the subject I found: http://sgros.blogspot.com/2013/01/seagate-disk-smart-values.html

AFAIK, the fields this'd apply to would be "Raw Read Error Rate" and "Seek Error Rate".

**Comment by kozlek** [comment]
There is no problem to add 16/24 format support. But this should be configured via configuration file. It is possible to apply this rule to specific hdd that is matched by name. Do you have Seagate hdd?

**Comment by jammi** [comment]
Three of the drives are Seagate, two different models.

**Comment by kozlek** [comment]
Please, share your HDD names here. I will add them to config. I need the names as they are displayed in HWMonitor if possible.

**Comment by jammi** [comment]
`ST2000DL001-9VT156` and `ST4000DM000-1F2168`

**Comment by jammi** [comment]
And here are screenshots of the drives in question: 
![ST4000DM000-1F2168](https://cloud.githubusercontent.com/assets/821320/24461248/38e105e4-14a9-11e7-8025-6b5a5f0e877f.png)
![ST2000DL003-9VT166](https://cloud.githubusercontent.com/assets/821320/24461249/39046034-14a9-11e7-9cc4-ed72ed28eaf0.png)
![ST4000DL001-9VT156](https://cloud.githubusercontent.com/assets/821320/24461250/39080dd8-14a9-11e7-97fe-c47980d125a7.png)

**Comment by kozlek** [comment]
You can try [this]( http://hwsensors.com/public/HWSensors.6.24-4-g0d00fecf.1425.Binaries.dmg)

**Comment by jammi** [comment]
Thank you, it works.
