### ISSUE TITLE
Is this code portable to linux?

### ISSUE THREAD

**Issue by shkronjax** [kozlek/HWSensors#365]
this code runs great on a mac...with the exception of the radeon sensor...How would I go about compiling this on linux?

**Comment by red-green** [comment]
https://github.com/groeck/lm-sensors/

**Comment by shkronjax** [comment]
I already have lm-sensors and xsensors interface installed. However, lm-sensors lacks support for mac 5.1 (mid 2010) when it comes to sensor names and some other features such as voltage etc...Since hwsensors opens up in xcode, I was wondering if anyone out there has the knowledge of cross-compiling or even making hesensors compatible with Ubuntu or other Linux flavors. The question is mainly directed towards the developers of this project. Thanks red-green for your input.

**Comment by red-green** [comment]
I think the problem is that this kernel extension is designed to integrate with fakeSMC which there didn't seem to be any reason to make for Linux. You'd have to see if anyone has done so, but I think the kernel extension differences between Mac and Linux might make it impossible.

**Comment by shkronjax** [comment]
Unhappily, I agree. Thank You for your answer.
