### ISSUE TITLE
CPUSensors not working Geforce GT 1030

### ISSUE THREAD

**Issue by chris1111** [kozlek/HWSensors#373]
macOS Sierra 10.12.6 Build (16G29)
The GPU does not appear in HWMonitor
I try with what you with propsed on another subject (HWSensors.6.25-12-g23039705.1438.Binaries.dmg) issue is the same

I also wonder how this fact it is that since the release of the Pascal drivers this problem is still not resolved ? Will be this the pascal cards are not compatible with HWMonitor ?
Thank you for your help and time

**Comment by dmatora** [comment]
@chris1111 fixed

**Comment by chris1111** [comment]
Thank you
