### ISSUE TITLE
AMD Vega Family Support

### ISSUE THREAD

**Issue by toohotz** [kozlek/HWSensors#383]
Not sure if you had plans for the Vega family @kozlek but wanted to see the interest level in adding support since Vega seems to be natively (at least the 64) supported in High Sierra.

If there's anything else you might need from me feel free to follow up 👍 
![Imgur](https://i.imgur.com/ICxKcgK.png)

**Comment by Gaulomatic** [comment]
I am interested as well.

**Comment by oscarbg** [comment]
+1

**Comment by Gaulomatic** [comment]
I have added support [here](https://github.com/kozlek/HWSensors/pull/394).
