### ISSUE TITLE
GPU Sensors NVIDIA GeForce GT 710 2047 Mo

### ISSUE THREAD

**Issue by chris1111** [kozlek/HWSensors#406]
Hi MR  @dmatora 
Possible to ad support for (Gigabyte) NVIDIA Geforce GT 710 2047mo
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/sans_t33.png)
This Graphics card works OOB on macOS Mojave 
Thank you

**Comment by dmatora** [comment]
I don't have the card to test it

**Comment by chris1111** [comment]
Ok thank you anyway

**Comment by MalikBehloul** [comment]
not acceleration graphic !!!
